### ISSUE TITLE
Offline install

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-td#46]
The target system for this application won't have an Internet connection.

So, we will have to produce a distribution that contains all dependencies.

We can expect the client to have installed node on the system, but we'll have to provide all npm packages.

Could we either:
* switch our packaging strategy so that all dependencies are in the GitHub repo?
* introduce a new build command that packages the app and all it's dependencies into a zip file?

**Comment by lilitkarapetyan** [comment]
Done. 
![picturemessage_c0agttbr hhw](https://user-images.githubusercontent.com/20753599/54604952-782cdd00-4a61-11e9-89a5-8212f201387a.png)

**Comment by IanMayo** [comment]
Ok, tried to reproduce script. First got this:

![image](https://user-images.githubusercontent.com/1108513/54607504-64c04880-4a46-11e9-9d89-6b937e901f36.png)

So, I thought _offline is missing, I'll try to install it_. So I did `npm i`, and got this:
![image](https://user-images.githubusercontent.com/1108513/54607567-8cafac00-4a46-11e9-91f7-aa8bee50daef.png)

Then I tried to do offline install again, but got this:
![image](https://user-images.githubusercontent.com/1108513/54607592-9b965e80-4a46-11e9-971b-bcd9ed93122e.png)

**Comment by IanMayo** [comment]
[oops @lilitkarapetyan   , when I tried to run it before, I was 4 commits behind master]

Have run again, offline install appeared to work.

But running server failed:
![image](https://user-images.githubusercontent.com/1108513/54624530-749b5500-4a65-11e9-9889-f799c7f6c816.png)

**Comment by lilitkarapetyan** [comment]
looks like there are not last updates.
git pull ?

**Comment by IanMayo** [comment]
Yes, have done `git pull` again.

`npm run offline-install` worked fine.

But, when I do `npm start` I still get this:
````
admins-Mac-Pro:serge-td ian$ npm start

> sergetd@1.0.0 start /Users/ian/git/serge-td
> node server.js

/Users/ian/git/serge-td/node_modules/bindings/bindings.js:91
        throw e
        ^

Error: dlopen(/Users/ian/git/serge-td/node_modules/leveldown/build/Release/leveldown.node, 1): no suitable image found.  Did find:
	/Users/ian/git/serge-td/node_modules/leveldown/build/Release/leveldown.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
	/Users/ian/git/serge-td/node_modules/leveldown/build/Release/leveldown.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/Users/ian/git/serge-td/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/Users/ian/git/serge-td/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sergetd@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sergetd@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ian/.npm/_logs/2019-03-20T12_47_40_880Z-debug.log
````

**Comment by IanMayo** [comment]
Ok, @lilitkarapetyan - we fixed this, it was a dependency on leveldown.  We'll have to distribute the leveldown installer with our deliverable.

**Comment by lilitkarapetyan** [comment]
Done
